/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from "@tanstack/react-router"

// Import Routes

import { Route as rootRoute } from "./app/__root"
import { Route as BaseImport } from "./app/_base"
import { Route as DashboardIndexImport } from "./app/dashboard/index"
import { Route as BaseIndexImport } from "./app/_base/index"
import { Route as DashboardDashboardImport } from "./app/dashboard/_dashboard"
import { Route as BaseLoginImport } from "./app/_base/login"
import { Route as DashboardDashboardPerfilImport } from "./app/dashboard/_dashboard/perfil"
import { Route as DashboardDashboardHomeImport } from "./app/dashboard/_dashboard/home"
import { Route as DashboardDashboardAjustesImport } from "./app/dashboard/_dashboard/ajustes"
import { Route as BaseBlogPostsImport } from "./app/_base/blog/_posts"
import { Route as BaseBlogPostsIndexImport } from "./app/_base/blog/_posts.index"
import { Route as BaseBlogPostIdPostImport } from "./app/_base/blog/$postId/_post"
import { Route as BaseBlogPostIdPostIndexImport } from "./app/_base/blog/$postId/_post.index"

// Create Virtual Routes

const DashboardImport = createFileRoute("/dashboard")()
const BaseBlogImport = createFileRoute("/_base/blog")()
const BaseBlogPostIdImport = createFileRoute("/_base/blog/$postId")()

// Create/Update Routes

const DashboardRoute = DashboardImport.update({
  path: "/dashboard",
  getParentRoute: () => rootRoute,
} as any)

const BaseRoute = BaseImport.update({
  id: "/_base",
  getParentRoute: () => rootRoute,
} as any)

const BaseBlogRoute = BaseBlogImport.update({
  path: "/blog",
  getParentRoute: () => BaseRoute,
} as any)

const DashboardIndexRoute = DashboardIndexImport.update({
  path: "/",
  getParentRoute: () => DashboardRoute,
} as any)

const BaseIndexRoute = BaseIndexImport.update({
  path: "/",
  getParentRoute: () => BaseRoute,
} as any)

const DashboardDashboardRoute = DashboardDashboardImport.update({
  id: "/_dashboard",
  getParentRoute: () => DashboardRoute,
} as any)

const BaseLoginRoute = BaseLoginImport.update({
  path: "/login",
  getParentRoute: () => BaseRoute,
} as any)

const BaseBlogPostIdRoute = BaseBlogPostIdImport.update({
  path: "/$postId",
  getParentRoute: () => BaseBlogRoute,
} as any)

const DashboardDashboardPerfilRoute = DashboardDashboardPerfilImport.update({
  path: "/perfil",
  getParentRoute: () => DashboardDashboardRoute,
} as any)

const DashboardDashboardHomeRoute = DashboardDashboardHomeImport.update({
  path: "/home",
  getParentRoute: () => DashboardDashboardRoute,
} as any)

const DashboardDashboardAjustesRoute = DashboardDashboardAjustesImport.update({
  path: "/ajustes",
  getParentRoute: () => DashboardDashboardRoute,
} as any)

const BaseBlogPostsRoute = BaseBlogPostsImport.update({
  id: "/_posts",
  getParentRoute: () => BaseBlogRoute,
} as any)

const BaseBlogPostsIndexRoute = BaseBlogPostsIndexImport.update({
  path: "/",
  getParentRoute: () => BaseBlogPostsRoute,
} as any)

const BaseBlogPostIdPostRoute = BaseBlogPostIdPostImport.update({
  id: "/_post",
  getParentRoute: () => BaseBlogPostIdRoute,
} as any)

const BaseBlogPostIdPostIndexRoute = BaseBlogPostIdPostIndexImport.update({
  path: "/",
  getParentRoute: () => BaseBlogPostIdPostRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_base": {
      id: "/_base"
      path: ""
      fullPath: ""
      preLoaderRoute: typeof BaseImport
      parentRoute: typeof rootRoute
    }
    "/_base/login": {
      id: "/_base/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof BaseLoginImport
      parentRoute: typeof BaseImport
    }
    "/dashboard": {
      id: "/dashboard"
      path: "/dashboard"
      fullPath: "/dashboard"
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    "/dashboard/_dashboard": {
      id: "/dashboard/_dashboard"
      path: "/dashboard"
      fullPath: "/dashboard"
      preLoaderRoute: typeof DashboardDashboardImport
      parentRoute: typeof DashboardRoute
    }
    "/_base/": {
      id: "/_base/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof BaseIndexImport
      parentRoute: typeof BaseImport
    }
    "/dashboard/": {
      id: "/dashboard/"
      path: "/"
      fullPath: "/dashboard/"
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof DashboardImport
    }
    "/_base/blog": {
      id: "/_base/blog"
      path: "/blog"
      fullPath: "/blog"
      preLoaderRoute: typeof BaseBlogImport
      parentRoute: typeof BaseImport
    }
    "/_base/blog/_posts": {
      id: "/_base/blog/_posts"
      path: "/blog"
      fullPath: "/blog"
      preLoaderRoute: typeof BaseBlogPostsImport
      parentRoute: typeof BaseBlogRoute
    }
    "/dashboard/_dashboard/ajustes": {
      id: "/dashboard/_dashboard/ajustes"
      path: "/ajustes"
      fullPath: "/dashboard/ajustes"
      preLoaderRoute: typeof DashboardDashboardAjustesImport
      parentRoute: typeof DashboardDashboardImport
    }
    "/dashboard/_dashboard/home": {
      id: "/dashboard/_dashboard/home"
      path: "/home"
      fullPath: "/dashboard/home"
      preLoaderRoute: typeof DashboardDashboardHomeImport
      parentRoute: typeof DashboardDashboardImport
    }
    "/dashboard/_dashboard/perfil": {
      id: "/dashboard/_dashboard/perfil"
      path: "/perfil"
      fullPath: "/dashboard/perfil"
      preLoaderRoute: typeof DashboardDashboardPerfilImport
      parentRoute: typeof DashboardDashboardImport
    }
    "/_base/blog/$postId": {
      id: "/_base/blog/$postId"
      path: "/$postId"
      fullPath: "/blog/$postId"
      preLoaderRoute: typeof BaseBlogPostIdImport
      parentRoute: typeof BaseBlogImport
    }
    "/_base/blog/$postId/_post": {
      id: "/_base/blog/$postId/_post"
      path: "/$postId"
      fullPath: "/blog/$postId"
      preLoaderRoute: typeof BaseBlogPostIdPostImport
      parentRoute: typeof BaseBlogPostIdRoute
    }
    "/_base/blog/_posts/": {
      id: "/_base/blog/_posts/"
      path: "/"
      fullPath: "/blog/"
      preLoaderRoute: typeof BaseBlogPostsIndexImport
      parentRoute: typeof BaseBlogPostsImport
    }
    "/_base/blog/$postId/_post/": {
      id: "/_base/blog/$postId/_post/"
      path: "/"
      fullPath: "/blog/$postId/"
      preLoaderRoute: typeof BaseBlogPostIdPostIndexImport
      parentRoute: typeof BaseBlogPostIdPostImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  BaseRoute: BaseRoute.addChildren({
    BaseLoginRoute,
    BaseIndexRoute,
    BaseBlogRoute: BaseBlogRoute.addChildren({
      BaseBlogPostsRoute: BaseBlogPostsRoute.addChildren({
        BaseBlogPostsIndexRoute,
      }),
      BaseBlogPostIdRoute: BaseBlogPostIdRoute.addChildren({
        BaseBlogPostIdPostRoute: BaseBlogPostIdPostRoute.addChildren({
          BaseBlogPostIdPostIndexRoute,
        }),
      }),
    }),
  }),
  DashboardRoute: DashboardRoute.addChildren({
    DashboardDashboardRoute: DashboardDashboardRoute.addChildren({
      DashboardDashboardAjustesRoute,
      DashboardDashboardHomeRoute,
      DashboardDashboardPerfilRoute,
    }),
    DashboardIndexRoute,
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_base",
        "/dashboard"
      ]
    },
    "/_base": {
      "filePath": "_base.tsx",
      "children": [
        "/_base/login",
        "/_base/",
        "/_base/blog"
      ]
    },
    "/_base/login": {
      "filePath": "_base/login.tsx",
      "parent": "/_base"
    },
    "/dashboard": {
      "filePath": "dashboard",
      "children": [
        "/dashboard/_dashboard",
        "/dashboard/"
      ]
    },
    "/dashboard/_dashboard": {
      "filePath": "dashboard/_dashboard.tsx",
      "parent": "/dashboard",
      "children": [
        "/dashboard/_dashboard/ajustes",
        "/dashboard/_dashboard/home",
        "/dashboard/_dashboard/perfil"
      ]
    },
    "/_base/": {
      "filePath": "_base/index.tsx",
      "parent": "/_base"
    },
    "/dashboard/": {
      "filePath": "dashboard/index.tsx",
      "parent": "/dashboard"
    },
    "/_base/blog": {
      "filePath": "_base/blog",
      "parent": "/_base",
      "children": [
        "/_base/blog/_posts",
        "/_base/blog/$postId"
      ]
    },
    "/_base/blog/_posts": {
      "filePath": "_base/blog/_posts.tsx",
      "parent": "/_base/blog",
      "children": [
        "/_base/blog/_posts/"
      ]
    },
    "/dashboard/_dashboard/ajustes": {
      "filePath": "dashboard/_dashboard/ajustes.tsx",
      "parent": "/dashboard/_dashboard"
    },
    "/dashboard/_dashboard/home": {
      "filePath": "dashboard/_dashboard/home.tsx",
      "parent": "/dashboard/_dashboard"
    },
    "/dashboard/_dashboard/perfil": {
      "filePath": "dashboard/_dashboard/perfil.tsx",
      "parent": "/dashboard/_dashboard"
    },
    "/_base/blog/$postId": {
      "filePath": "_base/blog/$postId",
      "parent": "/_base/blog",
      "children": [
        "/_base/blog/$postId/_post"
      ]
    },
    "/_base/blog/$postId/_post": {
      "filePath": "_base/blog/$postId/_post.tsx",
      "parent": "/_base/blog/$postId",
      "children": [
        "/_base/blog/$postId/_post/"
      ]
    },
    "/_base/blog/_posts/": {
      "filePath": "_base/blog/_posts.index.tsx",
      "parent": "/_base/blog/_posts"
    },
    "/_base/blog/$postId/_post/": {
      "filePath": "_base/blog/$postId/_post.index.tsx",
      "parent": "/_base/blog/$postId/_post"
    }
  }
}
ROUTE_MANIFEST_END */
